### ISSUE TITLE
Random Seed - Chapter 4

### ISSUE THREAD

**Issue by steviestevepy** [PacktPublishing/Hands-on-Neuroevolution-with-Python#2]
Hello and thank you for this repository! Very useful!

I have read the book and I am currently implementing and assessing the performance of NEAT on the Double Pole Balancing experiment from chapter 4.

I am trying to figure out how the random seed works in the experiment. By using the same seed I always get the same performance output. Where is the seed used in the whole approach and code?

Should the seed be changed for different runs?

Thank you

**Comment by yaricom** [comment]
Hello Stevie,

Thank you for an excellent question.

Neuroevolution is a stochastic process as every other genetic algorithm. Thus, it depends on the sequence of random numbers generated by the pseudo-random generator. In turn, the pseudo-random number generator generates the same sequence depending on the provided initial conditions (random seed).

So, we can say that each run using the same seed will produce the same output.

I'm using a fixed seed to ensure that you will get the same results as described in the book. However, you can modify the algorithm to use a new seed for each run and compare the results.

I hope my explanation helps.

Best regards,
Iaroslav

**Comment by steviestevepy** [comment]
> Hello Stevie,
> 
> Thank you for an excellent question.
> 
> Neuroevolution is a stochastic process as every other genetic algorithm. Thus, it depends on the sequence of random numbers generated by the pseudo-random generator. In turn, the pseudo-random number generator generates the same sequence depending on the provided initial conditions (random seed).
> 
> So, we can say that each run using the same seed will produce the same output.
> 
> I'm using a fixed seed to ensure that you will get the same results as described in the book. However, you can modify the algorithm to use a new seed for each run and compare the results.
> 
> I hope my explanation helps.
> 
> Best regards,
> Iaroslav

This is excellent! I was wondering if that was the case and now I have confirmation!
Thank you..
and thank you for your book! very useful!

Kind regards
