### ISSUE TITLE
Setting non-mating ablations.

### ISSUE THREAD

**Issue by steviestevepy** [PacktPublishing/Hands-on-Neuroevolution-with-Python#3]
Sorry to bother again.

I have one more question. After reading your book and reading the NEAT paper I would like to reproduce the experiments conducted in the paper. Especially, I am willing to reproduce the non-mating ablation described in the original NEAT paper. What are the key parameters in the config file that I should change, for the XOR experiment, in order to deactivate crossover ?

Thank you for your help

**Comment by yaricom** [comment]
Hello Stevie,

I believe you need to define your own implementation of the Reproduction Interface. 

More details at https://neat-python.readthedocs.io/en/latest/reproduction-interface.html#reproduction-interface-label

See also https://github.com/CodeReclaimers/neat-python/blob/c2b79c88667a1798bfe33c00dd8e251ef8be41fa/neat/reproduction.py#L183

Best regards,
Iaroslav

**Comment by steviestevepy** [comment]
Thank you for your support!

This is helpful. I was looking into it and I was considering something. Would setting the `survival_threshold` to `0` do the job of not allowing any members of any species to reproduce?

![tempsnip](https://user-images.githubusercontent.com/47188937/93310414-a75e0f00-f7fc-11ea-8b93-3bc5f97fa7e7.png)

Thanks again for your time and help!

Best regards
S

**Comment by yaricom** [comment]
Hi Stefano,

You definitely should try what you have found (setting survival_threshold to zero). Honestly, I'm not sure how NEAT-Python library will treat such as setting. However, I would be glad to hear from you about the result of this experiment.

Cheers,
Iaroslav

**Comment by steviestevepy** [comment]
Thank you again!

I will try this out and let you know the results of the experiment. 
Failing this I will tailor my reproduction interface as you suggested.

Kind regards

S
